config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  resources :users
  get 'sessions/new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :jams
  resources :comments
  put '/jam/:id/like', to: 'jams#like', as: 'like'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :jam
end

app/models/jam.rb
class Jam < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments

  def self.like(jam_id)
    jam = Jam.find_by(id: jam_id)
    jam.update(likes: (jam.likes + 1))
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password 
  has_one_attached :image
  has_many :jams
  has_many :comments

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, format: { with: VALID_EMAIL_REGEX}
  validates :password, length: { minimum: 6, maximum: 20}
  before_save :downcase_email

  def downcase_email
    self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :current_user

    def new
      @comment = Comment.new
      @jam = Jam.find_by(id: params[:format])
    end
  
    def create
      @comment = @user.comments.create(comment_params)
      @jam_owner = User.find(@comment.user_id)   
      @jam = Jam.find(@comment.jam_id)  
      if @comment.valid?
        redirect_to jam_path(@jam.id)
        flash[:newuser] = "You have commented on #{@jam_owner.name}'s post!"
      else
        flash[:error] = "Your comment could not be created"
        redirect_to new_comment_path
      end
  
    end

  
    private 
  
    def comment_params
      params.require(:comment).permit(:body, :user_id, :jam_id)
    end

    def current_user
      @user = User.find(session[:user_id])
    end
  
end

app/controllers/jams_controller.rb
class JamsController < ApplicationController

  def new
    @jam = Jam.new
  end

  def create
    @user = User.find(session[:user_id])
    @jam = @user.jams.create(jam_params)
    if @jam.valid?
      redirect_to jam_path(@jam.id)
      flash[:newuser] = "You have created a new post #{@user.name}!"
    else
      flash[:error] = "Your post could not be created"
      redirect_to new_jam_path
    end

  end

  def show 
    @jam = Jam.find(params[:id])
  end

  def index
    @jams = Jam.all.order(created_at: :desc)
  end

  def like
    Jam.like(params[:id])
    redirect_to jam_url(params[:id])
  end


  private 

  def jam_params
    params.require(:jam).permit(:image, :caption)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # def new
  # end

  def create 
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(session[:user_id])
      flash[:notice] = "Welcome #{@user.name}!"
    else
      redirect_to root_path
      flash[:error] = "Your login details were incorrect"
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show, :edit, :update, :destroy]
  
  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "You have successfully edited your account"
      redirect_to @user
    else
      flash[:error] = "Unable to edit user"
      render 'edit'
    end
  end

  def create 
    @user = User.create(user_params)
    if @user.valid?
      redirect_to root_path
      flash[:newuser] = "You have created your account #{@user.name}"
    else
      flash[:error] = "There was a problem with your details"
      redirect_to new_user_path
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :image)
  end

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/jams_helper.rb
module JamsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div>
  <%= form_for @comment do |f| %>
    <%= f.label :body, "Comment" %>
    <%= f.text_field :body %> 
    <%= f.hidden_field :jam_id, value: @jam.id %>
    <%= f.hidden_field :user_id, value: @user.id %>

    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/jams/index.html.erb
<% @jams.each do |jam| %>
  <p>
    <% user = User.find(jam.user_id) %>
    <%= "Posted by #{jam.user.name}!"%>
    <br>
    <%= image_tag jam.image, style: "width: 200px;" %>
    <br>
    <%= jam.caption %>
  </p>
  <%= link_to "See this Jam", jam_path(jam) %>
  <br>

<% end %>

app/views/jams/new.html.erb
<div>
  <%= form_for @jam do |f| %>
    <%= f.label :image, "Image" %>
    <%= f.file_field :image, class: "form-control" %> 
    <%= f.label :caption %>
    <%= f.text_field :caption %> 

    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/jams/show.html.erb
<p>
  <% user = User.find(@jam.user_id) %>
  <%= "Posted by #{@jam.user.name}!"%>
  <br>
  <%= image_tag @jam.image, style: "width: 200px;" %>
  <br>
  <%= @jam.caption %>
  <% @jam.comments.each do |comment| %>
  <% comment_user = User.find(comment.user_id) %>
    <p> <%= "#{comment.body}--#{comment_user.name}"%></p>
  <% end %>
</p>
<div>
  <%= button_to "Like", like_path(@jam.id), method: "put" %>
  <%= @jam.likes %> <%= @jam.likes == 1 ? "Like" : "Likes" %>
</div>


<div>
  <%= link_to "Add Comment", new_comment_path(@jam) %>
</div>
<br>

<div>
  <%= link_to "Edit Jam", edit_jam_path(@jam) %>
</div>
<br>

<div>
  <%= link_to "See other Jams", jams_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <main>
      <% flash.keys.each do |type| %>
        <div data-alert class="flash <%= type %> alert-box radius">
          <%= flash[type] %>
          <a href="" class="close">&times;</a>
        </div>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<h2> InstaJam </h2>


<%= form_for(:session , url: login_path, remote: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %> 
  <%= f.submit "Log in" %>
<% end %>
<br>

<%= link_to "Sign up", new_user_path %>

app/views/users/_form.html.erb
<div>
  <%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %> 
    <%= f.label :image, "Add a profile picture" %>
    <%= f.file_field :image, class: "form-control" %> 

    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>Edit user</h2>

<%= render 'form' %>

app/views/users/new.html.erb
<h3> Create a new user <h3>

<%= render 'form' %>

app/views/users/show.html.erb
<%= "#{@user.name}'s profile page" %>
<br>
<div>
  <%= link_to "Edit user", edit_user_path(@user) %>
</div>

<% if @user.image.attached? %>
  <%= image_tag @user.image, style: "display: block" %>
<% end %>

<br>
<div>
  <%= link_to "Create a new Jam", new_jam_path(@user) %>
</div>
<div>
  <%= link_to "See Jams", jams_path %>
</div>